[package]
name = "fuse-ard"
authors = ["RoccoDev <hey@rocco.dev"]
version = "0.1.0"
edition = "2021"

[dependencies]
ardain = { path = "../ardain" }
fuser = "0.14"
libc = "0.2"
anyhow = "1"
env_logger = "0.11"
xc3_lib = { git = "https://github.com/ScanMountGoat/xc3_lib", rev = "6bfc884" }