[package]
name = "ardain"
authors = ["RoccoDev <hey@rocco.dev"]
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.13.3"
thiserror = "1.0.58"
xc3_lib = { git = "https://github.com/ScanMountGoat/xc3_lib", rev = "6bfc884" }
