[package]
name = "ard-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
ardain = { path = "../ardain" }
anyhow = "1"
clap = { version = "4.5.4", features = ["derive"] }
rayon = "1.10"
indicatif = "0.17"